import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Rito Ramadhan", url: "https://github.com/mas-rito" }],
  icons: {
    icon: "/icons/white.png",
  },
};

export default function Home() {
  return (
    <main className="flex min-h-screen items-center justify-center">
      <h1>Hello World</h1>
    </main>
  );
}
